# Generated by Django 6.0.3 on 2026-05-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='authors',
        ),
        migrations.AlterField(
            model_name='author',
            name='title',
            field=models.CharField(blank=True, choices=[('ks', 'Ks.'), ('dr', 'Dr.'), ('prof', 'Prof.'), ('mr', 'Mr.'), ('ms', 'Ms.')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('polish', 'Polish'), ('spanish', 'Spanish'), ('french', 'French'), ('german', 'German'), ('other', 'Other')], max_length=20),
        ),
    ]
